### ISSUE TITLE
Execution rights missing on dfu-suffix and stm32l4-upload

### ISSUE THREAD

**Issue by cryptax** [FabienFerrero/UCA_AIOT#1]
Trying to compile an Arduino program, you get this error:

```
Library LoRaSpaceLib has been declared precompiled:
Using precompiled library in /home/axelle/.arduino15/packages/uca-aiot/hardware/stm32l4/0.0.4/libraries/LoRaSpaceLib/src/cortex-m4/fpv4-sp-d16-hard
fork/exec /home/axelle/.arduino15/packages/uca-aiot/hardware/stm32l4/0.0.4/tools/linux//dfu-suffix: permission denied
```

This can be solved by doing `chmod ugo+x dfu-suffix`.

Same, later, when trying to upload the program:

```
Library LoRaSpaceLib has been declared precompiled:
Using precompiled library in /home/axelle/.arduino15/packages/uca-aiot/hardware/stm32l4/0.0.4/libraries/LoRaSpaceLib/src/cortex-m4/fpv4-sp-d16-hard
Sketch uses 49800 bytes (20%) of program storage space. Maximum is 245760 bytes.
Library LoRaSpaceLib has been declared precompiled:
Using precompiled library in /home/axelle/.arduino15/packages/uca-aiot/hardware/stm32l4/0.0.4/libraries/LoRaSpaceLib/src/cortex-m4/fpv4-sp-d16-hard
Sketch uses 49800 bytes (20%) of program storage space. Maximum is 245760 bytes.
java.io.IOException: Cannot run program "/home/axelle/.arduino15/packages/uca-aiot/hardware/stm32l4/0.0.4/tools/linux/stm32l4-upload": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
```

This can be solved by doing `chmod ugo+x stm32l4-upload`

**Comment by nguyenmanhthao996tn** [comment]
We are highly appreciate your support!
It will be included in the next core version the permission granting on these files when installing. Thank you very much for your solution!
